### ISSUE TITLE
redis密码设置

### ISSUE THREAD

**Issue by xxllp** [gudegg/yunSpider#1]
请问这个是否能去掉，我简单去掉配置文件里面的参数会报错

**Comment by gudegg** [comment]
你直接留空就行 如果密码不存在 不要去掉password=这样就行

**Comment by xxllp** [comment]
但是还有个问题，我刚爬了一个就提示百度限制了，这个是被反扒了吧

**Comment by gudegg** [comment]
有可能 我这边爬没什么问题
